# This is a basic workflow to help you get started with Actions

name: Generate Devcard

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  devcard:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@2.0.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          devcard_id: dc7ab985949441238bf39f91f81afbdb
          commit_branch: devcard
          commit_filename: devcard.png
          commit_message: "chore: update ${filename}"
