name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: phuocantd
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to snake branch
        uses: crazy-max/ghaction-github-pages@v5
        with:
          build_dir: dist
          target_branch: snake
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
